spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mid_goods?autoReconnect=true&useSSL=false&characterEncoding=utf8&useUnicode=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mapper/**.xml

logging:
  level:
    root: info

