spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/data_types?autoReconnect=true&useSSL=false&characterEncoding=utf8&useUnicode=true
#    username: root
#    password: 123456
    url: jdbc:mysql://10.32.32.22:3306/mid_goods?autoReconnect=true&useSSL=false&characterEncoding=utf8&useUnicode=true
    username: mid_admin
    password: M1d@V1pK0d
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: mapper/**.xml

